{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ if .Values.externalSecret.name }}{{ .Values.externalSecret.name | quote }}{{ else }}{{ printf "%s-externalsecret" .Release.Name | trunc 63 | trimSuffix "-" | quote }}{{ end }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "24h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name | default "google-secret-manager-store" | quote }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind | default "SecretStore" | quote }}
  target:
    name: {{ if .Values.externalSecret.targetName }}{{ .Values.externalSecret.targetName | quote }}{{ else }}{{ printf "%s-secret" .Release.Name | trunc 63 | trimSuffix "-" | quote }}{{ end }}
    creationPolicy: Owner
  data:
    {{- range $container := .Values.containers }}
      {{- range $key, $val := $container.externalSecrets }}
    - secretKey: {{ $val | quote }}
      remoteRef:
        key: {{ $val | quote }}
      {{- end }}
    {{- end }}
{{- end }}

