backup:
  gcpServiceAccount: ""
  bucketName: ""

pooler:
  loadBalancerIP: ""

certificates:
  clusterIssuer: internal-ca

postgresClusterStatusServiceName: postgres-cluster-status

databases: []
  # Example:
  # - name: users
  #   owner: users_app
  #   passwordSecretName: users-app-credentials
