apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgres-pooler-rw
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  cluster:
    name: postgres-cluster
  type: rw
  instances: 3

  monitoring:
    enablePodMonitor: true

  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1500"
      default_pool_size: "50"
      min_pool_size: "10"
      reserve_pool_size: "10"
      server_idle_timeout: "600"
      server_login_retry: "15"

  serviceTemplate:
    metadata:
      annotations:
        networking.gke.io/internal-load-balancer-allow-global-access: "true"
        networking.gke.io/load-balancer-type: "Internal"
    spec:
      type: LoadBalancer
      loadBalancerIP: {{ .Values.pooler.loadBalancerIP | quote }}

  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
       -  name: pgbouncer
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              cnpg.io/poolerName: postgres-pooler-rw
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    cnpg.io/poolerName: postgres-pooler-rw
                topologyKey: kubernetes.io/hostname