apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-weekly-full-backup
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  schedule: "0 0 0 * * 0"
  backupOwnerReference: self
  cluster:
    name: postgres-cluster
  immediate: true
  target: prefer-standby